@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Full name</label><input type="text" name="name" required value="{{ old('name', $user?->name) }}" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Email</label><input type="email" name="email" required value="{{ old('email', $user?->email) }}" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Role</label><select name="role" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20">@foreach(['admin' => 'Administrator', 'manager' => 'Manager', 'agent' => 'Travel Agent', 'tour_guide' => 'Tour Guide', 'driver' => 'Driver', 'staff' => 'Staff'] as $role => $label)<option value="{{ $role }}" {{ old('role', $user?->role ?? 'staff') === $role ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Status</label><select name="status" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20">@foreach(['active', 'inactive'] as $status)<option value="{{ $status }}" {{ old('status', $user?->status ?? 'active') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Department</label><input type="text" name="department" value="{{ old('department', $user?->department) }}" placeholder="Operations" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Phone</label><input type="text" name="phone" value="{{ old('phone', $user?->phone) }}" placeholder="+63..." class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
</div>
@if ($errors->any())<div class="rounded-lg border border-error/30 bg-error/10 p-3 text-sm text-error"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex gap-3"><button type="submit" class="rounded-lg bg-primary px-4 py-2 text-white">{{ $user ? 'Update profile' : 'Save profile' }}</button><a href="{{ route('staff-profiles.index') }}" class="rounded-lg border border-border px-4 py-2">Cancel</a></div>
