@extends('layouts.app')
@section('title', 'Payment Methods')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-secondary">Financial operations</p><h2 class="mt-1 font-heading text-2xl font-semibold tracking-tight text-primary">Payment methods</h2><p class="mt-2 text-sm text-gray-500">Review payment activity and record customer payments by method.</p></div><a href="{{ route('bookings.index') }}" class="group inline-flex items-center gap-2 rounded-xl bg-secondary px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-secondary/20 transition-all duration-200 hover:-translate-y-0.5 hover:bg-primary active:translate-y-0 active:scale-95"><span>View bookings</span><span class="transition-transform duration-200 group-hover:translate-x-1">→</span></a></div>
    <div class="grid grid-cols-1 gap-4 md:grid-cols-5"><div class="rounded-2xl border border-border border-t-4 border-t-primary bg-card p-5 shadow-sm"><div class="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">{{ $summary['filtered'] ? 'Month total' : 'Total recorded' }}</div><div class="mt-3 font-heading text-2xl font-semibold text-primary">&#8369;{{ number_format($summary['total'], 2) }}</div></div><div class="rounded-2xl border border-border border-t-4 border-t-success bg-card p-5 shadow-sm"><div class="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">Paid</div><div class="mt-3 font-heading text-2xl font-semibold text-success">&#8369;{{ number_format($summary['paid'], 2) }}</div></div><div class="rounded-2xl border border-border border-t-4 border-t-warning bg-card p-5 shadow-sm"><div class="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">Partial</div><div class="mt-3 font-heading text-2xl font-semibold text-warning">&#8369;{{ number_format($summary['partial'], 2) }}</div></div><div class="rounded-2xl border border-border border-t-4 border-t-error bg-card p-5 shadow-sm"><div class="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">Refunded</div><div class="mt-3 font-heading text-2xl font-semibold text-error">&#8369;{{ number_format($summary['refunded'], 2) }}</div></div><div class="rounded-2xl border border-border border-t-4 border-t-secondary bg-card p-5 shadow-sm"><div class="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">Bookings</div><div class="mt-3 font-heading text-2xl font-semibold text-primary">{{ $summary['bookings'] }}</div></div></div>
    @if($summary['filtered'])
        <div class="flex flex-col gap-3 rounded-2xl border border-border bg-accent/5 px-5 py-3 sm:flex-row sm:items-center sm:justify-between"><div class="text-sm text-gray-600">Showing payments received in <span class="font-semibold text-primary">{{ date('F Y', mktime(0, 0, 0, (int) $filters['paid_month'], 1, (int) ($filters['paid_year'] ?? now()->year))) }}</span></div><a href="{{ route('payment-methods.index') }}" class="rounded-lg border border-border bg-white px-3 py-1.5 text-xs font-semibold text-primary transition hover:border-secondary hover:text-secondary">Clear filter</a></div>
    @endif
    <div class="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div class="border-b border-border bg-gradient-to-r from-primary/[0.04] to-transparent p-5"><p class="text-xs font-semibold uppercase tracking-[0.16em] text-gray-400">Transactions</p><h2 class="mt-1 font-heading text-xl font-semibold text-primary">Payment activity</h2><p class="mt-1 text-sm text-gray-500">Choose Finance on a booking to record a new payment.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-background text-[11px] font-semibold uppercase tracking-[0.12em] text-gray-500"><tr><th class="px-5 py-3.5">Booking</th><th class="px-5 py-3.5">Customer</th><th class="px-5 py-3.5">Method</th><th class="px-5 py-3.5">Amount</th><th class="px-5 py-3.5">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse ($payments as $payment)<tr class="transition hover:bg-background/70"><td class="px-5 py-4 font-semibold text-primary">{{ $payment->booking?->reference_no ?? 'HT-' . $payment->booking_id }}</td><td class="px-5 py-4">{{ $payment->booking?->customer_name ?? 'Unknown customer' }}</td><td class="px-5 py-4 capitalize">{{ str_replace('_', ' ', $payment->payment_method) }}</td><td class="px-5 py-4 font-semibold text-primary">&#8369;{{ number_format($payment->amount, 2) }}</td><td class="px-5 py-4"><span class="rounded-full {{ $payment->status === 'paid' ? 'bg-success/10 text-success' : ($payment->status === 'partial' ? 'bg-warning/10 text-warning' : ($payment->status === 'refunded' ? 'bg-error/10 text-error' : ($payment->status === 'cancelled' ? 'bg-error/10 text-error' : 'bg-gray-100 text-gray-600'))) }} px-2.5 py-1 text-xs font-semibold capitalize">{{ $payment->status }}</span></td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No payment transactions yet.</td></tr>@endforelse</tbody></table></div><div class="border-t border-border px-5 py-4">{{ $payments->links() }}</div></div>
    <div class="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div class="border-b border-border bg-gradient-to-r from-secondary/[0.05] to-transparent p-5"><p class="text-xs font-semibold uppercase tracking-[0.16em] text-gray-400">Payment entry</p><h2 class="mt-1 font-heading text-xl font-semibold text-primary">Open Finance by booking</h2><p class="mt-1 text-sm text-gray-500">Select a booking to record or review its payments.</p></div><div class="divide-y divide-border">@forelse ($bookings as $booking)<div class="flex flex-col gap-3 px-5 py-4 transition hover:bg-background/70 sm:flex-row sm:items-center sm:justify-between"><div><div class="font-semibold text-primary">{{ $booking->reference_no }}</div><div class="mt-1 text-xs text-gray-500">{{ $booking->customer_name }} · {{ $booking->tourPackage?->name ?? 'Package unavailable' }} · ₱{{ number_format($booking->total_amount, 2) }}</div></div><a href="{{ route('bookings.finance', $booking) }}" class="group inline-flex items-center justify-center gap-2 rounded-xl bg-secondary px-4 py-2 text-xs font-semibold text-white shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:bg-primary active:translate-y-0 active:scale-95"><span>Open Finance</span><span class="transition-transform duration-200 group-hover:translate-x-1">→</span></a></div>@empty<p class="px-5 py-8 text-center text-sm text-gray-400">No bookings available.</p>@endforelse</div></div>
</div>
@endsection
