@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Full name</label><input type="text" name="name" required value="{{ old('name', $user?->name) }}" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Email</label><input type="email" name="email" required value="{{ old('email', $user?->email) }}" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Role</label><select name="role" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20">@foreach(['admin', 'manager', 'agent', 'staff'] as $role)<option value="{{ $role }}" {{ old('role', $user?->role ?? 'staff') === $role ? 'selected' : '' }}>{{ ucfirst($role) }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Status</label><select name="status" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20">@foreach(['active', 'inactive'] as $status)<option value="{{ $status }}" {{ old('status', $user?->status ?? 'active') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Department</label><input type="text" name="department" value="{{ old('department', $user?->department) }}" placeholder="Operations" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Job title</label><input type="text" name="job_title" value="{{ old('job_title', $user?->job_title) }}" placeholder="Travel Coordinator" class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Phone</label><input type="text" name="phone" value="{{ old('phone', $user?->phone) }}" placeholder="+63..." class="w-full rounded-xl border border-border bg-background px-3 py-2.5 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20"></div>
    <div></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">{{ $user ? 'New password (optional)' : 'Password' }}</label><input type="password" name="password" {{ $user ? '' : 'required' }} class="w-full rounded-lg border border-border px-3 py-2"><p class="mt-1 text-xs text-gray-500">Minimum 8 characters.</p></div>
    <div><label class="mb-1 block text-sm font-medium text-gray-700">Confirm password</label><input type="password" name="password_confirmation" {{ $user ? '' : 'required' }} class="w-full rounded-lg border border-border px-3 py-2"></div>
</div>
@if ($errors->any())<div class="rounded-lg border border-error/30 bg-error/10 p-3 text-sm text-error"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex gap-3"><button type="submit" class="group inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-primary/15 transition-all duration-200 hover:-translate-y-0.5 hover:bg-secondary hover:shadow-xl active:translate-y-0 active:scale-95"><span>{{ $user ? 'Update profile' : 'Save profile' }}</span><span aria-hidden="true" class="transition-transform duration-200 group-hover:translate-x-1">→</span></button><a href="{{ route('staff-profiles.index') }}" class="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold transition hover:border-secondary hover:text-secondary">Cancel</a></div>
