@extends('layouts.app')
@section('title', match ($module) { 'revenue' => 'Revenue', 'expenses' => 'Expenses', 'commissions' => 'Commissions', default => 'Analytics Dashboard' })
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-secondary">Financial operations</p><h2 class="mt-1 font-heading text-2xl font-semibold tracking-tight text-primary">{{ match ($module) { 'revenue' => 'Revenue', 'expenses' => 'Expenses', 'commissions' => 'Commissions', default => 'Analytics Dashboard' } }}</h2><p class="mt-2 text-sm text-gray-500">Monitor cash flow, operating costs, partner obligations, and performance.</p></div><span class="rounded-xl border border-accent/20 bg-accent/5 px-3 py-2 text-xs font-medium text-accent">Live finance workspace</span></div>
    @if ($module === 'revenue')
        <div class="grid grid-cols-1 gap-4 md:grid-cols-3"><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Recognized revenue</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($revenue, 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Refunds</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($refunds, 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Net collected</div><div class="mt-2 text-2xl font-semibold text-success">PHP {{ number_format($revenue - $refunds, 2) }}</div></div></div>
        <div class="overflow-x-auto rounded-2xl border border-border bg-card shadow-sm"><div class="border-b border-border p-5"><h2 class="font-heading text-xl font-semibold text-primary">Revenue transactions</h2><p class="text-sm text-gray-500">Payments linked to confirmed and completed bookings.</p></div><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">Booking</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Method</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse($payments as $payment)<tr><td class="px-5 py-3 font-medium text-primary">{{ $payment->booking?->reference_no ?? '—' }}</td><td class="px-5 py-3">{{ $payment->booking?->customer_name ?? '—' }}</td><td class="px-5 py-3">PHP {{ number_format($payment->amount, 2) }}</td><td class="px-5 py-3 capitalize">{{ str_replace('_', ' ', $payment->payment_method) }}</td><td class="px-5 py-3 capitalize">{{ $payment->status }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No payment transactions yet.</td></tr>@endforelse</tbody></table><div class="border-t border-border px-5 py-4">{{ $payments->links() }}</div></div>
    @elseif ($module === 'expenses')
        <div class="rounded-2xl border border-border bg-card p-5 shadow-sm"><div class="mb-5"><h2 class="font-heading text-xl font-semibold text-primary">Expenses</h2><p class="text-sm text-gray-500">Record operating costs and other business expenses.</p></div><form method="POST" action="{{ route('expenses.store') }}" class="grid gap-4 md:grid-cols-3">@csrf<input name="description" required placeholder="Description" class="rounded-lg border border-border px-3 py-2"><input name="category" required placeholder="Category" class="rounded-lg border border-border px-3 py-2"><input type="number" name="amount" required min="0.01" step="0.01" placeholder="Amount" class="rounded-lg border border-border px-3 py-2"><input type="date" name="expense_date" required class="rounded-lg border border-border px-3 py-2"><select name="status" class="rounded-lg border border-border px-3 py-2"><option value="recorded">Recorded</option><option value="approved">Approved</option><option value="paid">Paid</option></select><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Record expense</button></form></div><div class="rounded-2xl border border-border bg-card shadow-sm"><div class="border-b border-border p-5"><span class="text-sm text-gray-500">Total expenses</span><div class="text-2xl font-semibold text-primary">PHP {{ number_format($totalExpenses, 2) }}</div></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">Description</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">Date</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse($records as $record)<tr><td class="px-5 py-3 font-medium text-primary">{{ $record->description }}</td><td class="px-5 py-3">{{ $record->category }}</td><td class="px-5 py-3">{{ $record->expense_date->format('d M Y') }}</td><td class="px-5 py-3">PHP {{ number_format($record->amount, 2) }}</td><td class="px-5 py-3 capitalize">{{ $record->status }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No expenses recorded.</td></tr>@endforelse</tbody></table></div><div class="border-t border-border px-5 py-4">{{ $records->links() }}</div></div>
    @elseif ($module === 'commissions')
        <div class="grid grid-cols-1 gap-4 md:grid-cols-3">@foreach($totals as $status => $total)<div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs capitalize text-gray-500">{{ $status }} commissions</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($total, 2) }}</div></div>@endforeach</div><div class="overflow-x-auto rounded-2xl border border-border bg-card shadow-sm"><div class="border-b border-border p-5"><h2 class="font-heading text-xl font-semibold text-primary">Partner commissions</h2><p class="text-sm text-gray-500">Track commission obligations linked to bookings.</p></div><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">Partner</th><th class="px-5 py-3">Booking</th><th class="px-5 py-3">Rate</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse($commissions as $commission)<tr><td class="px-5 py-3 font-medium text-primary">{{ $commission->partner?->name ?? '—' }}</td><td class="px-5 py-3">{{ $commission->booking?->reference_no ?? '—' }}</td><td class="px-5 py-3">{{ $commission->commission_rate }}%</td><td class="px-5 py-3">PHP {{ number_format($commission->commission_amount, 2) }}</td><td class="px-5 py-3 capitalize">{{ $commission->status }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No commissions recorded.</td></tr>@endforelse</tbody></table><div class="border-t border-border px-5 py-4">{{ $commissions->links() }}</div></div>
    @else
        @php $net = $analytics['revenue'] - $analytics['expenses'] - $analytics['commissions'] - $analytics['campaignSpend']; @endphp
        <div><h2 class="font-heading text-xl font-semibold text-primary">Analytics dashboard</h2><p class="text-sm text-gray-500">A financial overview of revenue, costs, commissions, and marketing spend.</p></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Revenue</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($analytics['revenue'], 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Expenses</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($analytics['expenses'], 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Commissions</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($analytics['commissions'], 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Campaign spend</div><div class="mt-2 text-2xl font-semibold text-primary">PHP {{ number_format($analytics['campaignSpend'], 2) }}</div></div><div class="rounded-2xl border border-border bg-card p-4 shadow-sm"><div class="text-xs text-gray-500">Net operating result</div><div class="mt-2 text-2xl font-semibold {{ $net >= 0 ? 'text-success' : 'text-error' }}">PHP {{ number_format($net, 2) }}</div></div></div><div class="rounded-2xl border border-border bg-card p-5 shadow-sm"><h3 class="mb-4 font-heading font-semibold text-primary">Monthly revenue</h3><div class="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">@foreach($analytics['monthlyRevenue'] as $month => $amount)<div class="rounded-lg bg-background p-3"><div class="text-xs text-gray-500">{{ date('M', mktime(0, 0, 0, $month, 1)) }}</div><div class="mt-1 font-semibold text-primary">PHP {{ number_format($amount, 0) }}</div></div>@endforeach</div></div>
    @endif
</div>
@endsection
