@extends('layouts.app')
@section('title', match ($module) { 'documents' => 'Customer Documents', 'applications' => 'Visa Applications', 'requirements' => 'Visa Requirements', 'checklist' => 'Document Checklist', 'expiration' => 'Expiration Tracking', default => 'Application Status' })
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-secondary">Documents & visa</p><h2 class="mt-1 font-heading text-2xl font-semibold tracking-tight text-primary">{{ match ($module) { 'documents' => 'Customer Documents', 'applications' => 'Visa Applications', 'requirements' => 'Visa Requirements', 'checklist' => 'Document Checklist', 'expiration' => 'Expiration Tracking', default => 'Application Status' } }}</h2><p class="mt-2 text-sm text-gray-500">Keep customer documents, visa requirements, and application progress organized.</p></div><span class="rounded-xl border border-accent/20 bg-accent/5 px-3 py-2 text-xs font-medium text-accent">Compliance workspace</span></div>
    @if ($module === 'documents')
        <div class="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 class="font-heading text-xl font-semibold text-primary">Customer documents</h2><p class="mb-5 text-sm text-gray-500">Upload and track documents attached to customer bookings.</p><form method="POST" action="{{ route('customer-documents.store') }}" enctype="multipart/form-data" class="grid gap-4 md:grid-cols-3">@csrf<select name="booking_id" required class="rounded-lg border border-border px-3 py-2"><option value="">Select booking</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}">{{ $booking->reference_no }} · {{ $booking->customer_name }}</option>@endforeach</select><input name="document_type" required placeholder="Document type e.g. Passport" class="rounded-lg border border-border px-3 py-2"><input type="file" name="document" required class="rounded-lg border border-border px-3 py-2"><input type="date" name="expires_on" class="rounded-lg border border-border px-3 py-2"><select name="status" class="rounded-lg border border-border px-3 py-2"><option value="submitted">Submitted</option><option value="verified">Verified</option><option value="rejected">Rejected</option><option value="expired">Expired</option></select><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Upload document</button></form></div><div class="overflow-x-auto rounded-2xl border border-border bg-card shadow-sm"><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">File</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Type</th><th class="px-5 py-3">Expires</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse($records as $record)<tr><td class="px-5 py-3 font-medium text-primary">{{ $record->file_name }}</td><td class="px-5 py-3">{{ $record->related?->customer_name ?? '—' }}</td><td class="px-5 py-3">{{ $record->document_type }}</td><td class="px-5 py-3">{{ $record->expires_on?->format('d M Y') ?: '—' }}</td><td class="px-5 py-3 capitalize">{{ $record->status }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No customer documents yet.</td></tr>@endforelse</tbody></table><div class="border-t border-border px-5 py-4">{{ $records->links() }}</div></div>
    @elseif ($module === 'applications')
        <div class="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 class="font-heading text-xl font-semibold text-primary">Visa applications</h2><p class="mb-5 text-sm text-gray-500">Track customer visa requests from draft to decision.</p><form method="POST" action="{{ route('visa-applications.store') }}" class="grid gap-4 md:grid-cols-3">@csrf<input name="customer_name" required placeholder="Customer name" class="rounded-lg border border-border px-3 py-2"><select name="booking_id" class="rounded-lg border border-border px-3 py-2"><option value="">Related booking (optional)</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}">{{ $booking->reference_no }} · {{ $booking->customer_name }}</option>@endforeach</select><input name="country" required placeholder="Destination country" class="rounded-lg border border-border px-3 py-2"><input name="visa_type" required placeholder="Visa type" class="rounded-lg border border-border px-3 py-2"><input type="date" name="travel_date" class="rounded-lg border border-border px-3 py-2"><input type="date" name="submitted_on" class="rounded-lg border border-border px-3 py-2"><select name="status" class="rounded-lg border border-border px-3 py-2"><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="processing">Processing</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Save application</button></form></div>@include('document-operations._applications-table', ['records' => $records])
    @elseif ($module === 'requirements')
        <div class="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 class="font-heading text-xl font-semibold text-primary">Visa requirements</h2><p class="mb-5 text-sm text-gray-500">Maintain the document requirements used for customer checklists.</p><form method="POST" action="{{ route('visa-requirements.store') }}" class="grid gap-4 md:grid-cols-3">@csrf<input name="country" required placeholder="Country" class="rounded-lg border border-border px-3 py-2"><input name="visa_type" required placeholder="Visa type" class="rounded-lg border border-border px-3 py-2"><input name="document_name" required placeholder="Required document" class="rounded-lg border border-border px-3 py-2"><input name="description" placeholder="Description" class="rounded-lg border border-border px-3 py-2"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="required" value="1" checked> Required</label><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Add requirement</button></form></div>
    @endif
    @if ($module === 'requirements' || $module === 'checklist')
        <div><h2 class="font-heading text-xl font-semibold text-primary">{{ $module === 'checklist' ? 'Document checklist' : 'Requirements library' }}</h2><p class="text-sm text-gray-500">{{ $module === 'checklist' ? 'Use these requirements when preparing customer visa documents.' : 'Available country and visa requirement definitions.' }}</p></div><div class="overflow-x-auto rounded-2xl border border-border bg-card shadow-sm"><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">Country</th><th class="px-5 py-3">Visa type</th><th class="px-5 py-3">Document</th><th class="px-5 py-3">Required</th><th class="px-5 py-3">Description</th></tr></thead><tbody class="divide-y divide-border">@forelse($records as $record)<tr><td class="px-5 py-3 font-medium text-primary">{{ $record->country }}</td><td class="px-5 py-3">{{ $record->visa_type }}</td><td class="px-5 py-3">{{ $record->document_name }}</td><td class="px-5 py-3">{{ $record->required ? 'Yes' : 'Optional' }}</td><td class="px-5 py-3">{{ $record->description ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No requirements defined.</td></tr>@endforelse</tbody></table><div class="border-t border-border px-5 py-4">{{ $records->links() }}</div></div>
    @endif
    @if ($module === 'expiration')
        <div><h2 class="font-heading text-xl font-semibold text-primary">Document expiration tracking</h2><p class="text-sm text-gray-500">Documents expiring within the next 90 days.</p></div><div class="overflow-x-auto rounded-2xl border border-border bg-card shadow-sm"><table class="w-full text-left text-sm"><thead class="text-gray-500"><tr><th class="px-5 py-3">Document</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Expires</th><th class="px-5 py-3">Days remaining</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-border">@forelse($records as $record)@php $days = now()->startOfDay()->diffInDays($record->expires_on, false); @endphp<tr><td class="px-5 py-3 font-medium text-primary">{{ $record->file_name }}</td><td class="px-5 py-3">{{ $record->related?->customer_name ?? '—' }}</td><td class="px-5 py-3">{{ $record->expires_on->format('d M Y') }}</td><td class="px-5 py-3 {{ $days <= 30 ? 'text-error font-semibold' : 'text-warning' }}">{{ $days < 0 ? 'Expired' : $days . ' days' }}</td><td class="px-5 py-3 capitalize">{{ $record->status }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-400">No documents nearing expiration.</td></tr>@endforelse</tbody></table><div class="border-t border-border px-5 py-4">{{ $records->links() }}</div></div>
    @endif
    @if ($module === 'status')
        <div><h2 class="font-heading text-xl font-semibold text-primary">Visa application status</h2><p class="text-sm text-gray-500">Monitor every customer application and its current decision stage.</p></div>@include('document-operations._applications-table', ['records' => $records])
    @endif
</div>
@endsection
